#!/bin/bash
argv0=$(basename "$0")

for dir in *; do
	if [ -x "$dir/$argv0" ]; then
		echo "===== START: $TEST_SUBDIR/$dir ===== "
		pushd "$dir" >/dev/null
		"./$argv0"
		echo "===== END: $TEST_SUBDIR/$dir (ret: $?) ===== "
		popd >/dev/null
	fi
done
