#!/bin/bash
a0base=$(basename "$0")

#tmpdir=$(mktemp -d) || exit 1
#trap "rm -rf $tmpdir" EXIT
tmpdir="$(pwd)/tmp"
mkdir "$tmpdir" || exit 1

export TEF_LOGS="$tmpdir/logs"
resultslog="$tmpdir/results"
exec 3>"$resultslog"
export TEF_RESULTS_FD="3"

tef-runner -a "$a0base" "$@"

echo
echo =======
echo SUMMARY:
passed=$(grep -c '^PASS[[:space:]]' "$resultslog")
echo - PASS: $passed
failed=$(grep -c '^FAIL[[:space:]]' "$resultslog")
echo - FAIL: $failed
echo =======

if [ "$failed" -gt 0 ]; then
	while read -r status tname; do
		if [ -s "$TEF_LOGS/${tname}.log" ]; then
			echo -----------------------------
			echo -e "${status}\t${tname}:"
			cat "$TEF_LOGS/${tname}.log"
			echo -----------------------------
		else
			echo -e "${status}\t${tname}"
		fi
	done < <(grep '^FAIL[[:space:]]' "$resultslog")
fi
