#!/bin/bash

# make any .sh files executable and *then* run ptef-runner

chmod +x *.sh

base=$(basename "$0")

# also report SKIP instead of FAIL when tests exit with 2

ptef-runner -a "$base" -x '0:PASS 2:SKIP FAIL' "$@"
