#!/bin/bash
a0base=$(basename "$0")
runner() { tef-runner -a "$a0base" "$@"; }

# custom setup, decide c3 exit code
export C3EXIT=123

# if any args are passed, use them instead
if [ "$#" -gt 0 ]; then
  runner "$@"
else
  # run all, but only on odd seconds
  if expr "$(date +%s)" % 2 >/dev/null; then
    runner "$@"
  fi
fi
