#!/bin/bash
# Test log rotation, it must not exceed .9

. testlib.bash

for i in {0..8}; do
	assert_ptef_mklog testname <<<"$i"
done
[ -d logs ]
[ -f logs/testname.log.8 ]
[ ! -f logs/testname.log.9 ]
assert_ptef_mklog testname <<<"9"
[ -f logs/testname.log.9 ]
[ ! -f logs/testname.log.10 ]
assert_ptef_mklog testname <<<"10"
[ -f logs/testname.log.9 ]
[ ! -f logs/testname.log.10 ]
# non-standard
[ ! -f logs/testname.log.0 ]
# check log file content - we rotated i=0 out,
# so .log is 10, .log.1 is 9, .., .log.9 is 1
assert_contents $'10\n' logs/testname.log
for i in {9..1}; do
	assert_contents "$((10-i))"$'\n' "logs/testname.log.$i"
done
