#!/bin/bash

. testlib.sh


function mkfile {
	make_arg_printer "$@"
}


# Other variables (PTEF_PREFIX / PTEF_LOGS / ..) are tested elsewhere


# Test that PTEF_RUN prints out a RUN status
function ptef_run {
	mkfile > executable
	chmod +x executable
	assert_ptef_runner > "$tmpdir/runner_out"
	assert_contents $'PASS[\t ]*/executable' "$tmpdir/runner_out"
	PTEF_RUN=1 assert_ptef_runner > "$tmpdir/runner_out"
	assert_contents $'RUN[\t ]*/executable\nPASS[\t ]*/executable' \
		"$tmpdir/runner_out"
}
# Test that cli -r option exports PTEF_RUN and the runner honors it
function ptef_run_opt {
	make_var_printer PTEF_RUN > executable
	chmod +x executable
	assert_ptef_runner -r > "$tmpdir/runner_out"
	assert_contents '1' exec_log
	assert_contents $'RUN[\t ]*/executable\nPASS[\t ]*/executable' \
		"$tmpdir/runner_out"
}

# Test that an open file descriptor passed via PTEF_RESULTS_FD receives
# the same results as stdout
function ptef_results_fd {
	mkfile > executable
	chmod +x executable
	exec {test_fd}>"$tmpdir/result_log"
	PTEF_RESULTS_FD="$test_fd" \
		assert_ptef_runner > "$tmpdir/runner_out"
	assert_grep '^PASS[[:space:]]\+/executable$' "$tmpdir/runner_out"
	assert_grep '^PASS[[:space:]]\+/executable$' "$tmpdir/result_log"
}

# Test that PTEF_NOLOGS results in executable stderr not being redirected
# and prevents logs from being created
function ptef_nologs {
	cat > executable <<-EOF
	#!/bin/bash
	echo "this is stderr" >&2
	EOF
	chmod +x executable
	ptef-runner >"$tmpdir/runner_out" 2>"$tmpdir/runner_err"
	assert_grep '^PASS[[:space:]]\+/executable$' "$tmpdir/runner_out"
	assert_contents 'this is stderr' logs/executable.log
	assert_nogrep '^this is stderr$' "$tmpdir/runner_err"
	rm -rf logs
	PTEF_NOLOGS=1 ptef-runner \
		>"$tmpdir/runner_out" 2>"$tmpdir/runner_err"
	assert_grep '^PASS[[:space:]]\+/executable$' "$tmpdir/runner_out"
	[ ! -d logs ]
	assert_contents 'this is stderr' "$tmpdir/runner_err"
}

# Test that cli -v option exports PTEF_NOLOGS and the runner honors it
function ptef_nologs_opt {
	make_var_printer PTEF_NOLOGS > executable
	echo 'echo "this is stderr" >&2' >> executable
	chmod +x executable
	ptef-runner -v >"$tmpdir/runner_out" 2>"$tmpdir/runner_err"
	assert_contents '1' exec_log
	assert_contents 'this is stderr' "$tmpdir/runner_err"
}

# Test that PTEF_COLOR controls result color output on both non-terminal
# and terminal-based stdout
function ptef_color {
	mkfile > executable
	chmod +x executable
	local colorpass=$'\e\[1;32mPASS\e\[0m'
	# output to file + no var = no color
	assert_ptef_runner >"$tmpdir/runner_out"
	assert_grep '^PASS[[:space:]]\+/executable$' "$tmpdir/runner_out"
	assert_ptef_report PASS testname >"$tmpdir/report_out"
	assert_contents $'PASS[\t ]*/testname' "$tmpdir/report_out"
	# output to file + var 0 = no color
	PTEF_COLOR=0 assert_ptef_runner >"$tmpdir/runner_out"
	assert_grep '^PASS[[:space:]]\+/executable$' "$tmpdir/runner_out"
	PTEF_COLOR=0 assert_ptef_report PASS testname >"$tmpdir/report_out"
	assert_contents $'PASS[\t ]*/testname' "$tmpdir/report_out"
	# output to file + var 1 = color
	PTEF_COLOR=1 assert_ptef_runner >"$tmpdir/runner_out"
	assert_grep "^$colorpass[[:space:]]\+/executable$" "$tmpdir/runner_out"
	PTEF_COLOR=1 assert_ptef_report PASS testname >"$tmpdir/report_out"
	assert_contents "$colorpass"$'[\t ]*/testname' "$tmpdir/report_out"
	# output to terminal + no var = color
	TEST_WRAPPER=ttee \
		assert_ptef_runner >"$tmpdir/runner_out"
	assert_grep "^$colorpass[[:space:]]\+/executable$" "$tmpdir/runner_out"
	TEST_WRAPPER=ttee \
		assert_ptef_report PASS testname >"$tmpdir/report_out"
	assert_contents "$colorpass"$'[\t ]*/testname' "$tmpdir/report_out"
	# output to terminal + var 0 = no color
	TEST_WRAPPER=ttee PTEF_COLOR=0 \
		assert_ptef_runner >"$tmpdir/runner_out"
	assert_grep '^PASS[[:space:]]\+/executable$' "$tmpdir/runner_out"
	TEST_WRAPPER=ttee PTEF_COLOR=0 \
		assert_ptef_report PASS testname >"$tmpdir/report_out"
	assert_contents $'PASS[\t ]*/testname' "$tmpdir/report_out"
	# output to terminal + var 1 = color
	TEST_WRAPPER=ttee PTEF_COLOR=1 \
		assert_ptef_runner >"$tmpdir/runner_out"
	assert_grep "^$colorpass[[:space:]]\+/executable$" "$tmpdir/runner_out"
	TEST_WRAPPER=ttee PTEF_COLOR=1 \
		assert_ptef_report PASS testname >"$tmpdir/report_out"
	assert_contents "$colorpass"$'[\t ]*/testname' "$tmpdir/report_out"
}


+ ptef_run
+ ptef_run_opt
+ ptef_results_fd
+ ptef_nologs
+ ptef_nologs_opt
+ ptef_color


run_tests "$@"
