#!/bin/bash
# Test that all ptef-* CLIs support -h (for help)

. testlib.bash

ret=0
ptef-runner -h >"$tmpdir/runner_out" 2>"$tmpdir/runner_err" || ret=$?
[ "$ret" -eq 0 ]
[ -s "$tmpdir/runner_err" ]
ret=0
ptef-report -h >"$tmpdir/report_out" 2>"$tmpdir/report_err" || ret=$?
[ "$ret" -eq 0 ]
[ -s "$tmpdir/report_err" ]
ret=0
ptef-mklog -h >"$tmpdir/mklog_out" 2>"$tmpdir/mklog_err" || ret=$?
[ "$ret" -eq 0 ]
[ -s "$tmpdir/mklog_err" ]
