#!/bin/bash
# Test some of the -x option sanity checking

. testlib.bash

function assert_runner_error {
	local ret=0
	ptef-runner "$@" >"$tmpdir/runner_out" 2>"$tmpdir/runner_err" || ret=$?
	[ "$ret" -ne 0 ]
	assert_contents '' "$tmpdir/runner_out"
	[ -s "$tmpdir/runner_err" ]
}

ret=0
assert_runner_error -x ''
assert_runner_error -x 'END'
assert_runner_error -x 'PASS END'
assert_runner_error -x ':PASS END'
assert_runner_error -x '0: END'
assert_runner_error -x '256:PASS END'
