#!/bin/bash
# Test that cli -d option exports PTEF_SHELL and the runner honors it

. testlib.bash

# run with args, so that we can actually print out the variable
make_var_printer PTEF_SHELL > executable
chmod +x executable
timeout 10 ptef-runner -d executable \
	>"$tmpdir/runner_out" 2>"$tmpdir/runner_err"
assert_contents $'1\n' exec_log
