#!/bin/bash
a0base=$(basename "$0")
runner() { tef-runner -a "$a0base" "$@"; }

# if any args are passed, use them instead
if [ "$#" -gt 0 ]; then
  runner "$@"
else
  # do not run 'y'
  # run par2 twice, reverse par1/par3 order
  runner \
    parametrized/par3 \
    parametrized/par2/arg1 \
    parametrized/par2/arg2 \
    parametrized/par1
  # args for part2 won't be visible in report because par2 would need to
  # behave like a runner and report results for them
fi
