#!/bin/bash
# Test that ptef_report exits with 2 (EAGAIN) when an output is locked
# and PTEF_NOWAIT is passed

. testlib.bash

touch "$tmpdir/results_fd_out"
exec {fd}>"$tmpdir/results_fd_out"
mkfifo "$tmpdir/lockfifo"
hold-lock "$tmpdir/lockfifo" >&"$fd" &
# wait for hold-lock to lock report_out
cat "$tmpdir/lockfifo"
PTEF_RESULTS_FD="$fd" timeout 10 ptef-report -n PASS testname \
	>"$tmpdir/report_out" 2>"$tmpdir/report_err" \
		|| echo $? >"$tmpdir/report_exitval"
# make hold-lock finish
cat "$tmpdir/lockfifo"
wait
assert_contents '' "$tmpdir/report_err"
# ptef-report should have exited without writing out results
assert_contents '' "$tmpdir/results_fd_out"
assert_contents '' "$tmpdir/report_out"
assert_contents $'2\n' "$tmpdir/report_exitval"
