#!/bin/sh
#
# this shows a simple test parametrization with just one added level of
# hierarchy (messing with TEF_PREFIX is not needed as we know that 'mount'
# or 'grep' won't be acting as runners)
#

check_cgroup() {
	tef-report RUN "$1"
	# no log created, too simple
	mount | grep "on /sys/fs/cgroup/$1 type cgroup (.*${1}"
	[ $? -eq 0 ] && tef-report PASS "$1" || tef-report FAIL "$1"
}

if [ "$#" -gt 0 ]; then
	while [ "$#" -gt 0 ]; do
		check_cgroup "$1"
		shift
	done
else
	for cgtype in freezer devices blkio hugetlb perf_event pids memory \
			cpuset cpu,cpuacct net_cls,net_prio; do
		check_cgroup "$cgtype"
	done
fi
