#!/bin/bash
# Test that ptef_report locks stdout when writing a result to it

. testlib.bash

touch "$tmpdir/report_out"

hold-lock >"$tmpdir/report_out" 2>"$tmpdir/lock_info" &
hold_pid=$!
prepend_cleanup "kill $hold_pid 2>/dev/null || true"  # safety

wait_lock "$tmpdir/lock_info"
! grep -q '^error' "$tmpdir/lock_info"

TEST_WRAPPER="timeout 2" \
	assert_ptef_report PASS testname >"$tmpdir/report_out" || true

# make hold-lock finish
kill -INT "$hold_pid"
wait
grep -q '^unlocked$' "$tmpdir/lock_info"
! grep -q '^error' "$tmpdir/lock_info"

# ptef-report should have timed out
assert_contents '' "$tmpdir/report_out"
