#!/bin/bash
# Test that cli -A re-sets PTEF_BASENAME, overriding any existing one

. testlib.bash

mkfile > executable
chmod +x executable
PTEF_BASENAME=varrun assert_ptef_runner -A optrun > "$tmpdir/runner_out"
assert_contents $'optrun\n' exec_log
