#!/bin/bash

# typically used by bigger projects
export PTEF_LOGS="$PWD/suite-logs"

# if specific tests were selected by relative path including tests/,
# strip 'tests/' from their paths
args=("${@#tests/}")

# save a copy of the results, outside tests/, for some post-processing
exec {RESULT_LOG}>result.log

pushd tests/ >/dev/null
PTEF_RESULTS_FD="$RESULT_LOG" ./run "${args[@]}"
ret="$?"
popd >/dev/null

exec {RESULT_LOG}>&-

# simulate as if this was us running inside 'tests'
exit "$ret"
