#!/bin/sh
#
# check for user-owned processes with RSS above 100M
#
# breaking the spec by not reporting RUN
#

. ../utils/proc_helpers.bash

for pid in $(proc_list_user_pids); do
	comm=$(proc_comm "$pid")
	rss=$(proc_rss "$pid")
	if [ "$rss" ]; then
		if [ "$rss" -le 102400 ]; then
			tef-report PASS "${pid}_${comm}"
		else
			tef-report FAIL "${pid}_${comm}"
			proc_show_rss "$pid"
		fi
	fi
done
