#!/bin/bash
# Test that PTEF_LOGS is used and works with absolute paths

. testlib.bash

mkdir subd
mkfile > subd/ptef-runner
chmod +x subd/ptef-runner
PTEF_LOGS="$PWD/testlogs" assert_ptef_runner > "$tmpdir/runner_out"
assert_contents "$PWD/testlogs"$'\n' subd/exec_log
[ ! -d logs ]
[ -f testlogs/subd.log ]
assert_contents $'stderr output\n' testlogs/subd.log
