#!/bin/bash
# Test that an unset PTEF_LOGS results in a 'logs' subdir in CWD

. testlib.bash

mkdir subd
mkfile > subd/ptef-runner
chmod +x subd/ptef-runner
assert_ptef_runner > "$tmpdir/runner_out"
assert_contents $'unset\n' subd/exec_log
[ -d logs ]
[ -f logs/subd.log ]
assert_contents $'stderr output\n' logs/subd.log
