#!/bin/bash
# Test that PTEF_LOGS can be relative (and is adjusted according to prefix)

. testlib.bash

mkfile > executable
chmod +x executable
mkdir testlogs
PTEF_LOGS=testlogs assert_ptef_runner > "$tmpdir/runner_out"
assert_contents $'testlogs\n' exec_log
[ ! -d logs ]
[ -f testlogs/executable.log ]
assert_contents $'stderr output\n' testlogs/executable.log
